import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronLeft, Send, Sparkles, Code2, Play } from 'lucide-react';
import { useAppStore } from '../store';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export function CodeScreen({ navigateTo }: { navigateTo: (screen: any) => void }) {
  const { chats, activeChatId, addChat, addMessage, settings, addNotification } = useAppStore();
  const [input, setInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState<'chat' | 'preview'>('chat');
  
  const chatEndRef = useRef<HTMLDivElement>(null);
  
  const activeChat = chats.find(c => c.id === activeChatId);
  const messages = activeChat?.messages || [];
  
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isGenerating, activeTab]);

  const handleSend = async () => {
    if (!input.trim() || isGenerating) return;
    
    let chatId = activeChatId;
    if (!chatId) {
      chatId = addChat({ title: input.slice(0, 20), type: 'code', messages: [] });
      useAppStore.getState().setActiveChat(chatId);
    }
    
    addMessage(chatId, { role: 'user', text: input });
    setInput('');
    setIsGenerating(true);

    try {
      const currentChat = useAppStore.getState().chats.find(c => c.id === chatId);
      const formattedMessages = currentChat!.messages.map(m => ({
        role: m.role,
        parts: [{ text: m.text }]
      }));
      
      const systemPrompt = "You are an expert web developer. When asked to create HTML, output a complete, single HTML file code inside a ```html ... ``` markdown block. Include any CSS (like Tailwind CDN) and JS within the same file. Make it beautiful and functional.";

      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: formattedMessages,
          engine: 'gemini',
          system: systemPrompt,
          apiKey: settings.apiKey,
        }),
      });
      const data = await res.json();
      
      if (res.ok) {
        addMessage(chatId, { role: 'model', text: data.text });
        
        // Check if there is valid HTML generated to notify user
        if (data.text.includes('```html')) {
           addNotification({ type: 'ai', message: 'Código gerado com sucesso! Vá para a aba Live Preview para ver.', effect: 'sparkle' });
        }
      } else {
        addMessage(chatId, { role: 'model', text: "Error: " + data.error });
        addNotification({ type: 'error', message: `Erro na geração de código: ${data.error}`, effect: 'shake' });
      }
    } catch (error) {
      addMessage(chatId, { role: 'model', text: "Failed to generate." });
      addNotification({ type: 'error', message: 'Falha de rede ao gerar código.', effect: 'shake' });
    } finally {
      setIsGenerating(false);
    }
  };

  const extractHtml = (text: string) => {
    const match = text.match(/```html\s*([\s\S]*?)\s*```/);
    return match ? match[1] : null;
  };

  // Find the last HTML code block generated by the model
  const lastHtmlMessage = [...messages].reverse().find(m => m.role === 'model' && extractHtml(m.text));
  const htmlContent = lastHtmlMessage ? extractHtml(lastHtmlMessage.text) : '';

  return (
    <motion.div 
      key="code"
      initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 20 }}
      transition={{ duration: 0.25, ease: "easeOut" }}
      className="flex flex-col h-full bg-[var(--bg-base)] text-[var(--text-main)] relative overflow-hidden"
    >
      <div className="flex items-center justify-between p-4 pt-6 relative z-10 bg-[var(--bg-surface)] border-b border-[var(--border-color)]">
        <button onClick={() => navigateTo('home')} className="p-2 -ml-2 text-[var(--text-muted)] hover:bg-[var(--text-main)]/10 rounded-full transition-colors">
          <ChevronLeft className="w-6 h-6" strokeWidth={2.5} />
        </button>
        <div className="flex items-center gap-2">
          <Code2 className="w-5 h-5 text-[var(--accent)]" />
          <h2 className="font-semibold tracking-wide">HTML Creator</h2>
        </div>
        <div className="w-10"></div>
      </div>

      <div className="flex bg-[var(--bg-panel)] p-1 m-4 rounded-xl border border-[var(--border-color)]">
        <button 
          onClick={() => setActiveTab('chat')}
          className={`flex-1 py-1.5 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-2 ${activeTab === 'chat' ? 'bg-[var(--bg-surface)] shadow-sm' : 'text-[var(--text-muted)]'}`}
        >
          <Code2 className="w-4 h-4" /> Code Chat
        </button>
        <button 
          onClick={() => setActiveTab('preview')}
          className={`flex-1 py-1.5 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-2 ${activeTab === 'preview' ? 'bg-[var(--bg-surface)] shadow-sm' : 'text-[var(--text-muted)]'}`}
        >
          <Play className="w-4 h-4" /> Live Preview
        </button>
      </div>

      {activeTab === 'chat' ? (
        <>
          <div className="flex-1 overflow-y-auto p-4 space-y-6 custom-scrollbar relative z-10">
            {messages.length === 0 && (
              <div className="h-full flex flex-col items-center justify-center text-center opacity-60">
                <Code2 className="w-12 h-12 mb-4" />
                <p className="text-lg font-medium">Describe the webpage</p>
                <p className="text-sm">"Create a landing page for a coffee shop..."</p>
              </div>
            )}
            
            {messages.map((msg) => (
              <motion.div 
                initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                key={msg.id} 
                className={`flex gap-3 max-w-full ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                {msg.role === 'model' && (
                  <div className="w-8 h-8 rounded-full bg-[var(--accent)] shrink-0 flex items-center justify-center shadow-md">
                    <Sparkles className="w-4 h-4 text-white" />
                  </div>
                )}
                <div className={`max-w-[280px] md:max-w-[500px] rounded-[24px] px-5 py-4 flex flex-col ${
                  msg.role === 'user'
                    ? 'bg-[var(--accent)] text-white rounded-br-sm'
                    : 'bg-[var(--bg-surface)] text-[var(--text-main)] rounded-bl-sm border border-[var(--border-color)] shadow-sm'
                }`}>
                  <div className="text-[14.5px] leading-[1.6] markdown-body overflow-hidden">
                    <Markdown remarkPlugins={[remarkGfm]}>{msg.text}</Markdown>
                  </div>
                </div>
              </motion.div>
            ))}
            {isGenerating && (
              <div className="flex gap-3 max-w-full justify-start">
                 <div className="w-8 h-8 rounded-full bg-[var(--accent)] shrink-0 flex items-center justify-center shadow-md">
                   <Sparkles className="w-4 h-4 text-white" />
                 </div>
                 <div className="bg-[var(--bg-surface)] text-[var(--text-main)] rounded-[24px] rounded-bl-sm border border-[var(--border-color)] px-5 py-4 flex items-center gap-1.5 h-[56px] shadow-sm">
                    <motion.div animate={{ scale: [1, 1.2, 1], opacity: [0.4, 1, 0.4] }} transition={{ repeat: Infinity, duration: 1 }} className="w-1.5 h-1.5 bg-[var(--text-main)]/60 rounded-full" />
                    <motion.div animate={{ scale: [1, 1.2, 1], opacity: [0.4, 1, 0.4] }} transition={{ repeat: Infinity, duration: 1, delay: 0.2 }} className="w-1.5 h-1.5 bg-[var(--text-main)]/60 rounded-full" />
                    <motion.div animate={{ scale: [1, 1.2, 1], opacity: [0.4, 1, 0.4] }} transition={{ repeat: Infinity, duration: 1, delay: 0.4 }} className="w-1.5 h-1.5 bg-[var(--text-main)]/60 rounded-full" />
                 </div>
              </div>
            )}
            <div ref={chatEndRef} className="h-4" />
          </div>

          <div className="shrink-0 p-4 bg-[var(--bg-base)] border-t border-[var(--border-color)] z-20">
            <div className="flex items-center gap-3 w-full">
              <div className="flex-1 flex items-center bg-[var(--bg-surface)] rounded-3xl pr-1.5 focus-within:ring-1 focus-within:ring-[var(--border-color)] transition-colors h-14 border border-[var(--border-color)]">
                <input 
                  type="text"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                  placeholder="Describe your HTML..." 
                  className="flex-1 bg-transparent h-full pl-5 focus:outline-none text-[16px]"
                />
                <button 
                  onClick={handleSend}
                  disabled={!input.trim() || isGenerating}
                  className="w-10 h-10 rounded-full bg-[var(--accent)] text-white flex items-center justify-center disabled:opacity-50"
                >
                  <Send className="w-4 h-4 ml-0.5" />
                </button>
              </div>
            </div>
          </div>
        </>
      ) : (
        <div className="flex-1 flex flex-col w-full h-full p-4 relative z-10">
          {htmlContent ? (
            <div className="w-full h-full bg-white rounded-xl overflow-hidden border border-[var(--border-color)] shadow-inner">
               <iframe 
                 srcDoc={htmlContent}
                 title="Preview"
                 sandbox="allow-scripts allow-forms"
                 className="w-full h-full border-none bg-white"
               />
            </div>
          ) : (
             <div className="h-full flex flex-col items-center justify-center text-center opacity-60">
                <Play className="w-12 h-12 mb-4" />
                <p className="text-lg font-medium">No preview available</p>
                <p className="text-sm">Generate some HTML code first.</p>
              </div>
          )}
        </div>
      )}
    </motion.div>
  );
}
